#!/usr/bin/perl

#
# Copyright (C) 2015 Nethesis S.r.l.
# http://www.nethesis.it - support@nethesis.it
# 
# This script is part of NethServer.
# 
# NethServer is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License,
# or any later version.
# 
# NethServer is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
# 
# You should have received a copy of the GNU General Public License
# along with NethServer.  If not, see <http://www.gnu.org/licenses/>.
#

use strict;
use NethServer::Password;

chmod 0600, '/usr/share/ocsinventory-reports/ocsreports/install.php';

# check if ocsweb db exists
if ( -d '/var/lib/mysql/ocsweb' ) {
    exit 0;
}

# generate random db pass
my $db_pass = NethServer::Password::store('ocsinventory');

open(my $fh, '|-', '/usr/bin/mysql -B') || die("[ERROR] Could not open mysql process");
print $fh qq(
create database ocsweb;
grant all privileges on ocsweb.* to 'ocs'\@'localhost' identified by '$db_pass';
flush privileges;
use ocsweb
\\. /usr/share/ocsinventory-reports/ocsreports/files/ocsbase_new.sql
update operators set passwd='!!' where id='admin';
);
close ($fh) || die("[ERROR] ocs inventory DB initialization FAILED");

